#!/usr/bin/env python3
"""Reproduce the Deng Jinzhu Day 3 UNAPPROVED calculation-data package.

This script only replays the internal 1,000-run Monte Carlo data. It does not
produce an API success, human approval, recommendation, or a reviewed artifact.
The recorded source-hash check prevents a superficially similar codebase from
being used to claim reproduction of the delivered JSON.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from simulation_day3.monte_carlo import run_unapproved_monte_carlo
from app.portable_io import write_json_utf8_lf

EXPECTED_ENGINE_HASHES = {
    "monte_carlo.py": "daaaf84bb5abeeff7b89413ee9d0d5e4d6fd7e8da48bd1985daf360eac755da8",
    "models.py": "26504bc029e704fc125e6afb57bc6592f2caf111ea54ba4e05a81e9df462b5ca",
    "policy.py": "0dd84f4f390254a5897f73c6e96a9db54650b295d32ca8a85c9d0bc536dc9d47",
}
FILENAMES = (
    "deng_day3_monte_carlo_full_UNAPPROVED.json",
    "deng_day3_matrix_deltas_UNAPPROVED.json",
    "deng_day3_formula_traces_UNAPPROVED.json",
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def write_json(path: Path, payload: object) -> None:
    """Write byte-identical UTF-8/LF JSON even when this script runs on Windows."""
    write_json_utf8_lf(path, payload)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, required=True, help="empty or new output directory")
    parser.add_argument("--expected-manifest", type=Path, help="manifest from the delivered data package")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    actual_hashes = {name: sha256(ROOT / "simulation_day3" / name) for name in EXPECTED_ENGINE_HASHES}
    if actual_hashes != EXPECTED_ENGINE_HASHES:
        raise SystemExit(
            "Source does not match the delivered data package's engineSourceSha256. "
            f"expected={EXPECTED_ENGINE_HASHES}; actual={actual_hashes}")

    args.out.mkdir(parents=True, exist_ok=True)
    request = json.loads((ROOT / "examples/simulate_request_v1.json").read_text(encoding="utf-8"))
    policy = json.loads((ROOT / "simulation_day3/examples/UNAPPROVED_MC_POLICY.json").read_text(encoding="utf-8"))
    preview = run_unapproved_monte_carlo(request, policy, project_root=ROOT)
    if preview["engineSourceSha256"] != EXPECTED_ENGINE_HASHES:
        raise SystemExit("Runtime output engine hashes differ from the recorded delivery hashes")

    write_json(args.out / FILENAMES[0], preview)
    matrix_data = {
        "kind": "CAUSORA_DENG_DAY3_MATRIX_DELTAS_ONLY_V1",
        "status": preview["status"],
        "decisionReady": False,
        "reviewStatus": preview["reviewStatus"],
        "policyStatus": preview["policyStatus"],
        "sourceDataVersion": preview["sourceDataVersion"],
        "formulaVersion": preview["formulaVersion"],
        "previewId": preview["previewId"],
        "seed": preview["seed"],
        "weeks": preview["weeks"],
        "monteCarloRuns": preview["monteCarloRuns"],
        "unitPricesUsd": preview["unitPricesUsd"],
        "distributionProvenance": preview["distributionProvenance"],
        "inputHashesSha256": preview["inputHashesSha256"],
        "engineSourceSha256": preview["engineSourceSha256"],
        "computedMatrix": preview["computedMatrix"],
        "decisionDeltas": preview["decisionDeltas"],
        "constraintScreening": preview["constraintScreening"],
        "note": "Actual seeded Monte Carlo data generated by Deng Jinzhu's Day3 engine. No human review, recommendation, or API success envelope is included.",
    }
    write_json(args.out / FILENAMES[1], matrix_data)
    traces_data = {
        "kind": "CAUSORA_DENG_DAY3_FORMULA_TRACES_ONLY_V1",
        "status": preview["status"],
        "decisionReady": False,
        "reviewStatus": preview["reviewStatus"],
        "policyStatus": preview["policyStatus"],
        "sourceDataVersion": preview["sourceDataVersion"],
        "formulaVersion": preview["formulaVersion"],
        "previewId": preview["previewId"],
        "seed": preview["seed"],
        "weeks": preview["weeks"],
        "monteCarloRuns": preview["monteCarloRuns"],
        "distributionProvenance": preview["distributionProvenance"],
        "formulaTraces": preview["formulaTraces"],
        "note": "Each path is sampleRunIndex=0, one realised stochastic trial. It is not an average or expected path; matrix values use all Monte Carlo runs.",
    }
    write_json(args.out / FILENAMES[2], traces_data)

    manifest = {
        "generatedAtUtc": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "owner": "Deng Jinzhu",
        "scope": "Day 3 simulation/data only",
        "status": preview["status"],
        "reviewStatus": preview["reviewStatus"],
        "policyStatus": preview["policyStatus"],
        "previewId": preview["previewId"],
        "sourceDataVersion": preview["sourceDataVersion"],
        "formulaVersion": preview["formulaVersion"],
        "seed": preview["seed"],
        "weeks": preview["weeks"],
        "monteCarloRuns": preview["monteCarloRuns"],
        "engineSourceSha256": actual_hashes,
        "artifacts": {
            filename: {"bytes": (args.out / filename).stat().st_size, "sha256": sha256(args.out / filename)}
            for filename in FILENAMES
        },
    }
    write_json(args.out / "deng_day3_data_manifest.json", manifest)

    if args.expected_manifest:
        expected = json.loads(args.expected_manifest.read_text(encoding="utf-8"))
        mismatches = []
        for filename in FILENAMES:
            expected_digest = expected["artifacts"][filename]["sha256"]
            if manifest["artifacts"][filename]["sha256"] != expected_digest:
                mismatches.append(filename)
        if preview["previewId"] != expected["previewId"]:
            mismatches.append("previewId")
        if mismatches:
            raise SystemExit(f"Reproduction mismatch: {', '.join(mismatches)}")
        print("REPRODUCTION_PASS: previewId and all three delivered data-file SHA-256 values match.")
    else:
        print("REPRODUCTION_COMPLETE: pass --expected-manifest to compare delivery hashes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
